# -*- coding: utf-8 -*-
"""SENAI-Python-Atividade1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1am7PFS_PCzUGnuQk0CQt7ySOi1imAbVt

# **ATIVIDADES**

## Atividade 1
"""

x = 4
x1 = 9
x2 = 5

x_result = (((2 + 5 ) * 3) + x + 5) < x1
print(x_result)
x_result = (((2 + 5) * 3) + (x + 5 + x1) == (x + 6 + x2 * 2))
print(x_result)
x_result = (((3 * 6) + x - 3) < x2)
print(x_result)
x_result = (((7 * 8) > (x + 4 - x1) < (x * 2 + x2 * 9)))
print(x_result)

"""## Atividade 2"""

N = 25

n_result = N > 20 and N < 30
print(n_result)

N1 = 26

n_result = N1 < 20 or N1 > 30
print(n_result)

a = 11
b = 0

ab_result = a > 10 and b <= 5
print(ab_result)

a = 10
b = 5

ab_result1 = a >= 10 or b < 5
print(not ab_result1)