# -*- coding: utf-8 -*-
"""SENAI-Python-Atividade2-MEDIA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YAP0i0cG4ArAx8KPgwrd6XbjZq1-ZB7_

programa media_aluno

var

  nota1, nota2, media : inteiro

  inicio

  leia (nota1, nota2)

  media <- (nota1 + nota2) / 2

  se(media) entao

  Aprovado

  senao

  Reprovado

  fim_se
"""

nota1 = float(input("Insira a primeira nota: "))
nota2 = float(input("Insira a segunda nota: "))

media = (nota1 + nota2) / 2

print("Sua media foi: " , media)

if media >= 7:
  print("Aprovado")
else:
  print("Reprovado")