# -*- coding: utf-8 -*-
"""SENAI-Python-Lista-Atividades-1-IF-ELSE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GaTGBUsRiPiITwjIljT_JWmjXp6Enjci

# Lista de atividades

## 1 - Leia dois números, faça a soma e apresente caso seja maior que 15
"""

n1 = float(input("Insira o primeiro valor: "))
n2 = float(input("Insira o segundo valor: "))

resultado = n1 + n2
print("O resultado e: ",resultado)

if resultado > 15:
 print("E maior que 15")

"""## 2 - Faça um programa que recebendo um valor inteiro, informe se o número é positivo, negativo ou neutro."""

n = int(input("Insira o valor: "))

if n == 0:
  print("o valor e Neutro")
elif n > 0:
  print("o valor ePositivo")
else:
  print("o valor e Negativo")

"""## Nova seção 3 - Leia a idade e informe se a pessoa é maior ou menor de idade"""

idade = int(input("Insira a idade: "))

if idade > 18:
  print("Maior de idade")
else:
  print("Menor de idade")

"""## 4 - Faça um programa que pergunte a temperatura atual para o usuário e mostre uma mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.

"""

clima = float(input("Insira a temperatura: "))

if clima < 20:
  print("Frio")
elif clima >= 20 and clima <= 25:
  print("Agradavel")
else:
  print("Calor")

"""## 5 - Faça um programa em linguagem Python que leia dois números inteiros e informe se estes são iguais ou diferentes."""

n1 = int(input("Insira o primeiro valor: "))
n2 = int(input("Insira o segundo valor: "))

if n1 == n2:
  print("Iguais")
else:
 print("Diferentes")

"""## 6. Escreva um programa que verifique a validade de uma senha fornecida pelo usuário. A senha válida é o número 1234. Devem ser impressas as seguintes mensagens:
* ACESSO PERMITIDO caso a senha seja válida.
* ACESSO NEGADO caso a senha seja inválida.
"""

senha = int(input("Insira a senha: "))

if senha == 1234:
  print("ACESSO PERMITIDO")
else:
  print("ACESSO NEGADO")

"""## 7 - Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas menor do que 7, informar que o aluno está de exame; se a média for menor do que 5 informar que o aluno foi reprovado."""

nota1 = float(input("Insira a primeira nota: "))
nota2 = float(input("Insira a segunda nota: "))

media = (nota1 + nota2) / 2

print("Sua media foi: " , media)

if media >= 7:
  print("Aprovado")
elif media >= 5 and media < 7:
  print("Esta de exame")
else:
  print("Reprovado")

"""## 8 - Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os gols de cada time) e informe se o resultado foi um empate, se a vitória foi do primeiro time ou do segundo time."""

golTimeA = int(input("Insira a quantidade de gols do time A: "))
golTimeB = int(input("Insira a quantidade de gols do time B: "))

if golTimeA == golTimeB:
 print("Empate")
elif golTimeA > golTimeB:
 print("Vitoria do time A")
else:
 print("Vitoria do time B")

"""## 9 - Faça um Programa que pergunte em que turno você estuda. Peça para digitar M - matutino ou V - Vespertino ou N - Noturno. Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso."""

turno = str(input("Insira a sigla M, V ou N: "))

if turno == "M" or turno == "m":
 print("Bom Dia!")
elif turno == "V" or turno == "V":
 print("Boa Tarde!")
elif turno == "N" or turno ==  "n":
 print("Boa Noite!")
else:
 print("Invalido")

"""## 10 - Faça um programa que solicite ao usuário sua idade, depois disso, exiba a classificação etária de acordo com as faixas de valores:
* Criança para 0 até 11 anos;
* Adolescente para 12 até 18 anos;
* Jovem para 19 até 24 anos;
* Adulto para 25 até 40 anos;
* Meia Idade para 41 até 60 anos;
* Idoso acima de 60 anos.


"""

idade = int(input("Insira a idade: "))

if idade >= 0 and idade <= 11:
  print("Criança")
elif idade >= 12 and idade <= 18:
  print("Adolescente")
elif idade >= 19 and idade <= 24:
  print("Jovem")
elif idade >= 25 and idade <= 40:
  print("Adulto")
elif idade >= 41 and idade <= 60:
  print( "Meia Idade")
elif idade > 60:
  print( "Idoso")
else:
  print("Invalido")

"""## 11 - As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:
* salários até RS 280,00 (incluindo) : aumento de 20%
* salários entre RS 280,00 e RS 700,00 : aumento de 15%
* salários entre RS 700,00 e RS 1500,00 : aumento de 10%
* salários de RS 1500,00 em diante : aumento de 5%

Após o aumento ser realizado, informe na tela:

* o salário antes do reajuste;
* o percentual de aumento aplicado;
* o valor do aumento;
* o novo salário, após o aumento.

"""

salario = float(input("Insira o salario: "))

if salario <= 280:
 aumento = salario * 0.2
 reajuste = salario + (salario * 0.2)
 print(f"Seu salario e de {salario} com percentual de aumento de 20% com o valor aumentado de {aumento}, e o novo salario ficou RS {reajuste} ")

elif salario >= 280 and salario < 700:
  aumento = salario * 0.15
  reajuste = salario + (salario * 0.15)
  print(f"Seu salario e de {salario} com percentual de aumento de 15% com o valor aumentado de {aumento}, e o novo salario ficou RS {reajuste} ")

elif salario >= 700 and salario < 1500:
  aumento = salario * 0.2
  reajuste = salario + (salario * 0.2)
  print(f"Seu salario e de {salario} com percentual de aumento de 10% com o valor aumentado de {aumento}, e o novo salario ficou RS {reajuste} ")

elif salario >= 1500:
  aumento = salario * 0.05
  reajuste = salario + (salario * 0.05)
  print(f"Seu salario e de {salario} com percentual de aumento de 5% com o valor aumentado de {aumento}, e o novo salario ficou RS {reajuste} ")

"""## 12 - Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.

"""

n = int(input("Insira um numero de 1 a 6: "))

if n == 1:
  print("Domingo")
elif n == 2:
  print("Segunda")
elif n == 3:
  print("Terca")
elif n == 4:
  print("Quarta")
elif n == 5:
  print( "Quinta")
elif n == 6:
  print( "Sexta")
else:
  print("Invalido")

"""## 13. Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta do usuário, faça a devida conversão."""

opcao = input("Bem-Vindo ao conversor de temperatura. Escolha a opcao A para converter C para F ou F para C:")

if opcao == "A" or opcao == "a":
 c = float(input("Insira uma temperatura em Celsius: "))
 conversao = c * 1.8 + 32
 print("C convertido para F fica:", conversao)

elif opcao == "B" or opcao == "b":
 f = float(input("Insira uma temperatura em Fahrenheit: "))
 conversao = (f - 32) * 1.8
 print("F convertido para C fica:", conversao)

else:
  print("Invalido")

"""## 14. Faça um programa que receba a idade de uma pessoa e imprima sua condição (obrigatória, optativa ou proibida), em relação ao ato de votar, conforme apresentado abaixo:
* Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
* Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar
(optativo);
* Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar
(obrigatório);
* Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).

"""

idade = int(input("Insira a idade: "))

if idade < 16:
  print("proibido")
elif idade >= 16 and idade < 18:
  print("optativo")
elif idade >= 18 and idade < 65:
  print("obrigatório")
elif idade >= 65:
  print("optativo")
else:
  print("Invalido")

"""## 15. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:

* “Telefonou para a vítima? “
* “Esteve no local do crime?”
* “Mora perto da vítima? “
* “Devia para a vítima? “
* “Já trabalhou com a vítima? “

O programa deve no final emitir uma classificação sobre a participação da pessoa
no crime. Se a pessoa responder positivamente a 2 questões ela deve ser
classificada como “Suspeita”, entre 3 e 4 como “Cúmplice” e 5 como “Assassino“.

"""

sim = 0

resposta1 = (input("Telefonou para a vítima?"))
if resposta1 == "sim" or "Sim" or "SIM":
 sim += 1

resposta2 = (input("Esteve no local do crime?"))
if resposta2 == "sim" or "Sim" or "SIM":
 sim += 1

resposta3 = (input("Mora perto da vítima?"))
if resposta3 == "sim" or "Sim" or "SIM":
 sim += 1

resposta4 = (input("Devia para a vítima?"))
if resposta4 == "sim" or "Sim" or "SIM":
 sim += 1

resposta5 = (input("Já trabalhou com a vítima? "))
if resposta5 == "sim" or "Sim" or "SIM":
 sim += 1

if sim == 2:
 print("Suspeita")
elif sim == 3 and sim == 4:
  print("Cúmplice")
elif sim == 5:
  print("Assassino")
else:
  print("Inocente")

"""## 16 - Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

produto1 = float(input("Insira o valor do primeiro produto: "))
produto2 = float(input("Insira o valor do segundo produto: "))
produto3 = float(input("Insira o valor do terceiro produto: "))

if produto1 < produto2 and produto1 < produto3:
 print("Produto 1 custa" , produto1 , "e e o mais barato")
if produto2 < produto1 and produto2 < produto3:
 print("Produto 2 custa" , produto2 , "e e o mais barato")
if produto3 < produto1 and produto3 < produto2:
 print("Produto 3 custa" , produto3 , "e e o mais barato")