# -*- coding: utf-8 -*-
"""SENAI-Python-Aula1-Operadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tSYEhZmkD43ftTbIZRoJnpsOCGT4kAJA
"""

print('Hello World')

"""# **Operadores Aritimeticos**

Adição +

Subtração -

Multiplicação *

Divisão /

Divisão // -> com apenas o resultado inteiro 2,5 = 2

Modulo % -> pega apenas o resto da divisão Exemplo 5%2 = 1

Exponenciação ** -> 2²
"""

a = 6+4*2
b = 4*9+5
c = ((6+7)*9)
d = (15+20-30)
e = 6 +5**2
print('O resultado de A foi:' , a)
print('O resultado de B foi:' , b)
print('O resultado de C foi:' , c)
print('O resultado de D foi:' , d)
print('O resultado de E foi:' , e)

"""# **Operadores de atribuiçao**"""

x = 8
print('O resultado de X:',x)
x += 5
print('O resultado de X:',x)
x -= 4
print('O resultado de X:',x)
x *= 20
print('O resultado de X:',x)
x /=2
print()

"""# **Operadores de comparaçao**

Maior >

Menor <

Igual a ==

Atribuição =

Diferente =!

Maior ou igual a >=

Menor ou igual a <=
"""

x = 8
x1 = 3

X_result = x < x1
print('O resultado de X:',X_result)
X_result = x == x1
print('O resultado de X:',X_result)
X_result = x>= x1
print('O resultado de X:',X_result)
X_result = x != x1
print('O resultado de X:',X_result)

"""# **Operadores logicos**

**AND(E)** -> retorna **TRUE** se todas as condições forem verdadeiras, caso contrario **FALSE**

**OR(OU)** -> Retorna **TRUE** de uma das condições for verdadeiro, caso contrario **FALSE**

**NOT(NAO)** -> Inverte o resultado: Se o resultado da expressão for **TRUE**, o operador retorna **FALSE**

**AND = &&**

**OR = ||**

**NOT = !**

# **Operador de indentidade**

**IS** -> Retorna **TRUE** se as variáveis comparadas forem o mesmo objeto

**IS NOT** -> Retorna **TRUE** se as variáveis comparadas não forem o mesmo objeto
"""

x1 = "botafogo"
x2 = "falmengo"
x3 = "botafogo"

x_result = x1 is x3
print(x_result)
x_result = x1 is not x2
print(x_result)
x_result = x1 is x2
print(x_result)
x_result = x2 is not x3
print(x_result)

"""# **Operadores de associacao**

**IN** -> Retorna **TRUE** caso o valor seja encontrado na sequencia

**NOT IN** -> Retorna **TRUE** caso o valor não seja encontrado na sequencia
"""

frutas = ["banana","laranja","uva","ameixa"]

x1 = "banana"
x2 = "laranja"
x3 = "abacaxi"

x_result = x1 in frutas
print(x_result)
x_result = x1 not in frutas
print(x_result)
x_result = x2 not in frutas
print(x_result)
x_result = x3 in frutas
print(x_result)